version: "3.9"

services:
  db:
    image: postgres:13.2
    container_name: postgres_compose
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db-volumne:/var/lib/postgres/data

  app:
    build: 
      context: API
      dockerfile: Dockerfile
    container_name: fastapi_compose
    restart: always
    environment:
      DB_CONN: ${DOCKER_DB_CONN}
    ports:
      - "8000:8000"
    depends_on:
      - db